### ISSUE TITLE
Image caching performance

### ISSUE THREAD

**Issue by igorkulman** [Q42/Q42.WinRT#13]
I am using ImageExtensions and my app has performance problems. I use it on tens of images in ListView. When the ListView loads the data, the whole UI freezes until the ImageExtensions load and cache all the images. I think there should be some queue or something so the images are not processed at the same time.

**Comment by Hoshinokoe** [comment]
The slowest operation is check if file exists. I implemented separate folder for image caching and store in the memory downloaded file list. So performance is much better. 

Maybe it will be usefull for you.

**Comment by igorkulman** [comment]
Any news on this?

**Comment by igorkulman** [comment]
I tried the solution suggested by @Hoshinokoe and the performance is much better. The only drawback is that I need to initialize the component at app startup by fetching the files list.

**Comment by michielpost** [comment]
Can you send a pull request with this change?

**Comment by igorkulman** [comment]
Sent
