### ISSUE TITLE
Win8.1 Check if file exists before getting/deleting

### ISSUE THREAD

**Issue by joaopbnogueira** [Q42/Q42.WinRT#14]
First of all, thank you for the excellent work on the framework.

I've been using it on WinRT 8.1 platforms and there is something that's bugging me.

Whenever I do DataCache.Delete, or .GetFromCache, if for some reason the file(key) does not exist, an exception is thrown.

Would it be possible to not throw it, and instead check if the file exists first?

I understand that under concurrency situations a race condition may exist, but this approach would be preferable, right?

Solution Example:

http://blogs.msdn.com/b/shashankyerramilli/archive/2014/02/17/check-if-a-file-exists-in-windows-phone-8-and-winrt-without-exception.aspx

Thanks.

**Comment by michielpost** [comment]
The exception is only thrown internally in the WinRT library. The app that is using the library does not get the exception when getting or deleting a key that does not exist. So it's not really a problem.

I've implemented the Windows Phone solution for Q42.WinRT.Phone.
But the main Q42.WinRT assembly which is compatible with Windows and Windows Phone Universal apps can't use this solution. Check the comments on the blog you posted:
quote:
"On Windows 8 and WP8.1 XAML app you should just use the "Handling exception method", that is a bit faster than looping over all files."

As I said, the exception is handled internally. So it's not a problem for apps using the library.

**Comment by joaopbnogueira** [comment]
I've only mentioned it because exception throwing has an impact on the performance of the application, that was the only reason.

As for the WinRT solution I thought that this might work


`public async Task<bool> isFilePresent(string fileName)
 {
 var item = await ApplicationData.Current.LocalFolder.TryGetItemAsync(fileName);
 return item != null;
 }`

Best,

**Comment by michielpost** [comment]
Yes that would work for WinRT. But the TryGetItemAsync method is only available in Windows 8.1. This library is also compatible with 8.0. 
When Windows 10 will become available I'll probably drop support for 8.0 and will use the TryGetItemAsync. Thanks!
