### ISSUE TITLE
WebDataCache delete by Uri not working

### ISSUE THREAD

**Issue by minglini** [Q42/Q42.WinRT#16]
Hi,
im using Q42 in my WP8.1 app in my ListItem, binding the CacheUri to MyImage (property of my entity):

`<Image  q42controls:ImageExtensions.CacheUri="{Binding MyImage}"/>`

Then, at some point, i´d like to clear the cache of one image, and i´m doing this:
`WebDataCache.Delete(new Uri(CurrentEntity.MyImage));`

But it is not working, the library still returns the cached image.

I´ve already tried with `await DataCache.ClearAll();` and `await WebDataCache.ClearAll();` and the images are still cached!

There is something more i need to do?

**Comment by michielpost** [comment]
Just did some testing and the WebDataCache.ClearAll() does work.
However if the WebDataCache folder is in use, it fails with a UnauthorizedAccessException, which is catched internally.

So you'll have to call WebDataCache.ClearAll() when the folder is not in use yet, maybe when starting your app?

**Comment by minglini** [comment]
I think this is really the problem, because `await WebDataCache.Delete` was throwing a UnauthorizedAccessException. The problem is that i need to clear some specific image caches even when the WebDataCache is already in use... I need to update them. There is some way to do that?

**Comment by michielpost** [comment]
You can use WebDataCache.Delete(Uri uri) with the URI of the Original image url.
Or GetAsync(Uri uri, bool forceGet = false) with the Original image URI and a forceGet = true to overwrite the image.

**Comment by minglini** [comment]
I´ve tried using the GetAsync method like this:
`await WebDataCache.GetAsync(new Uri(CurrentEntity.MyImageUrl), true);`
and i get an UnauthorizedAccessException. 

I cannot update the image in the application start, i need to update it after the WebDataCache was already in use. There is some other way that does not throw UnauthorizedAccessException?

**Comment by minglini** [comment]
The real question here is: There is some way to change the cached image when the library is already used (WebDataCache folder is in use) in previous pages?

**Comment by michielpost** [comment]
Fixed with PR #25
