### ISSUE TITLE
Cannot install nuget package into a wpa81 project

### ISSUE THREAD

**Issue by igorkulman** [Q42/Q42.WinRT#23]
Could not install package 'Q42.WinRT.Portable 1.0.11.42'. You are trying to install this package into a project that targets 'WindowsPhoneApp, Version=v8.1', but the package does not contain any assembly references or content files that are com
patible with that framework. For more information, contact the package author.

**Comment by michielpost** [comment]
Please install the latest version of this package. That one does have support for Windows Phone 8.1 / wpa81.
The version of the package you are installing now (1.0.11.42) was released when Windows Phone 8.1 did not even exist yet.
