### ISSUE TITLE
HashCode changes when the app restarts

### ISSUE THREAD

**Issue by daemun** [Q42/Q42.WinRT#24]
In UWP, GetHashCode method in extension method "ToCacheKey(this Uri uri)" changes everytime the app restart.

**Comment by michielpost** [comment]
I did a small test with a Windows 8.1 universal app and the ToCacheKey method returned the same value every time.

Which Uri are you using and are you creating a 8.1 or windows 10 universal app?

**Comment by daemun** [comment]
It's a windows 10 universal app. Any uri, even string hashcode will change when app restart.

**Comment by daemun** [comment]
http://ericlippert.com/2011/02/28/guidelines-and-rules-for-gethashcode/

and

https://msdn.microsoft.com/en-us/library/system.string.gethashcode.aspx 

> The hash code itself is not guaranteed to be stable. Hash codes for identical strings can differ across versions of the .NET Framework and across platforms (such as 32-bit and 64-bit) for a single version of the .NET Framework. In some cases, **they can even differ by application domain.**
As a result, **hash codes should never be used outside of the application domain in which they were created**, they should never be used as key fields in a collection, and **they should never be persisted.**
