### ISSUE TITLE
One more StorageType

### ISSUE THREAD

**Issue by startewho** [Q42/Q42.WinRT#28]
In Win10 system, a new StorageType Called LocalCache
will the enum StorageType will add this

**Comment by michielpost** [comment]
Thanks, great suggestion. I'm going to do a little rewrite so you can use any folder for your storage and the library won't need to be updated when new folders become available.

**Comment by michielpost** [comment]
You can now use any StorageFolder for the StorageHelper, also the LocalCacheFolder:
private StorageHelper<List<string>> storageHelper = new StorageHelper<List<string>>(Windows.Storage.ApplicationData.Current.LocalCacheFolder);

New release (1.5.0.42) will be on NuGet soon. Currently having some NuGet updating issues.

**Comment by startewho** [comment]
Thanks so mush. Great work
