### ISSUE TITLE
Will store the setting data by Serializer

### ISSUE THREAD

**Issue by startewho** [Q42/Q42.WinRT#29]
When I use the SettingsHelper, if I want to store a List<string> to the setting file. I have to firstly  Serializer the list and then use SettingsHelper.Set("key",list<string>).
So will there a option or default  Serializer the data before store them in setting file?

**Comment by michielpost** [comment]
No, the SettingsHelper is just an abstraction layer on top of ApplicationData.Current.LocalSettings (NETFX) and IsolatedStorageSettings.ApplicationSettings (WP8). It does not help you with Serialization.

Pull Request is welcome if you're going to make that functionality :)
