### ISSUE TITLE
How to get the local image path which is cached in WP 8.1

### ISSUE THREAD

**Issue by sharath1989** [Q42/Q42.WinRT#30]
I am already binding q42controls:ImageExtensions.CacheUri in XAML.
Now how to get the cached image as a string/Uri value in C#.

Just by passing the Server Uri link I need to get local cached Uri link.

**Comment by michielpost** [comment]
You can call WebDataCache.GetLocalUriAsync(Uri uri), that gives you the Uri to the locally cached file.
