### ISSUE TITLE
Not able to delete the file using Q42.WinRT.Data.WebDataCache.Delete(uri)

### ISSUE THREAD

**Issue by sharathm1** [Q42/Q42.WinRT#31]
I have stored images and i want to delete the files based on my specific conditions.

```
List<Article> list = await db.QueryAsync<Article>("select imgSource from Article where section_id = " + section_id);

await Q42.WinRT.Data.WebDataCache.Init();

foreach (Article article in list)
{
         KeyValuePair<string,string> keyValue = Q42.WinRT.Data.WebDataCache.GetFileReferenceByUri(new Uri(article.imgSource));

         await Q42.WinRT.Data.WebDataCache.Delete(new Uri(keyValue.Value));

 }
```
I made sure article.imgSource has the uri and after fetching using GetFileReferenceByUri the value is also same. When delete is called an exception is thrown.with the message as "Value cannot be null.
Parameter name: key"

**Comment by michielpost** [comment]
What's the result of
`Q42.WinRT.Data.WebDataCache.GetFileReferenceByUri(new Uri(article.imgSource));`

Is that null maybe?

You can get the source for Q42.WinRT, use it in your project and debug to see where the error happens exactly. Or maybe you can create a small sample project that reproduces this problem.

**Comment by sharath1989** [comment]
Hello michiel,  I have created a sample win phone 8.1 app which you can run and see.
When deleting it throws exception.   Here is the Download link : [http://1drv.ms/1ncsqWY](url)

**Comment by michielpost** [comment]
The file can't be deleted when it is in use  / visible in a view.
You'll first have to clear all references to it / navigate to another view and unload the other view from memory, before you can delete it.

**Comment by michielpost** [comment]
Thanks. It's fixed. You can download a new version of Q42.WinRT on NuGet.

**Comment by sharath1989** [comment]
Thanks michiel for the fix.
