### ISSUE TITLE
Option to limit cache size.

### ISSUE THREAD

**Issue by sust86** [Q42/Q42.WinRT#7]
It would be great if there is any option to set a limit of the used cache space. If the limit exceeds the longest not modified files could be deleted?

p.s. Great work so far!! Thanks!!

**Comment by michielpost** [comment]
Thanks. This is now available on the DataCache and the WebDataCache. The both have a Clear method which has a maxSize (bytes) as input. It will delete old files first untill the max size is reached.

You can run this on application start.

My advice is to first call DataCache.ClearInvalid to delete the cache items that are expired.
